import {
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Code2,
  FileText,
  Hammer,
  Package,
  Puzzle,
} from "lucide-react";

export const TEMPLATE_CATEGORIES = [
  "All",
  "General",
  "Products",
  "Services",
  "Construction",
  "Software",
  "Events",
  "Custom",
];

export const TEMPLATE_SECTIONS = {
  company: { id: "company", label: "Company Information" },
  client: { id: "client", label: "Client Information" },
  text: { id: "text", label: "Introduction" },
  overview: { id: "overview", label: "Project Overview" },
  event: { id: "event", label: "Event Details" },
  items: { id: "items", label: "Product / Items" },
  materials: { id: "materials", label: "Materials List" },
  timeline: { id: "timeline", label: "Timeline / Milestones" },
  summary: { id: "summary", label: "Pricing Summary" },
  payment: { id: "payment", label: "Payment Information" },
  terms: { id: "terms", label: "Terms & Conditions" },
  notes: { id: "notes", label: "Notes" },
  signature: { id: "signature", label: "Signature" },
  divider: { id: "divider", label: "Spacer / Divider" },
};

export const QUOTATION_TEMPLATES = [
  {
    id: "standard",
    name: "Standard Quotation",
    category: "General",
    description: "General quotation for most businesses and clients.",
    icon: FileText,
    iconClass: "bg-blue-50 text-blue-500",
    sections: [
      "company",
      "client",
      "text",
      "items",
      "summary",
      "terms",
      "notes",
      "signature",
    ],
  },
  {
    id: "product",
    name: "Product Sales",
    category: "Products",
    description: "Quotation for selling physical products or items.",
    icon: Package,
    iconClass: "bg-red-50 text-red-500",
    sections: [
      "company",
      "client",
      "items",
      "summary",
      "payment",
      "terms",
      "signature",
    ],
  },
  {
    id: "service",
    name: "Service Proposal",
    category: "Services",
    description: "Quotation for agencies, consulting and service providers.",
    icon: BriefcaseBusiness,
    iconClass: "bg-emerald-50 text-emerald-500",
    sections: [
      "company",
      "client",
      "overview",
      "items",
      "timeline",
      "summary",
      "terms",
      "signature",
    ],
  },
  {
    id: "construction",
    name: "Construction Quote",
    category: "Construction",
    description: "For construction and building projects.",
    icon: Hammer,
    iconClass: "bg-amber-50 text-amber-500",
    sections: [
      "company",
      "client",
      "text",
      "items",
      "materials",
      "summary",
      "payment",
      "terms",
      "signature",
    ],
  },
  {
    id: "software",
    name: "Software Solution",
    category: "Software",
    description: "For software, system development and IT solutions.",
    icon: Code2,
    iconClass: "bg-violet-50 text-violet-500",
    sections: [
      "company",
      "client",
      "overview",
      "items",
      "timeline",
      "summary",
      "payment",
      "terms",
      "signature",
    ],
  },
  {
    id: "event",
    name: "Event Quotation",
    category: "Events",
    description: "For events, seminars and special occasions.",
    icon: CalendarDays,
    iconClass: "bg-cyan-50 text-cyan-500",
    sections: [
      "company",
      "client",
      "event",
      "items",
      "summary",
      "payment",
      "terms",
      "signature",
    ],
  },
  {
    id: "custom",
    name: "Custom Layout",
    category: "Custom",
    description: "Use a saved custom quotation layout.",
    icon: Puzzle,
    iconClass: "bg-slate-100 text-slate-600",
    sections: ["company", "client", "text", "items", "summary", "signature"],
  },
];

export const CUSTOM_TEMPLATE = {
  id: "custom-built",
  name: "Custom Quotation",
  category: "Custom",
  description: "A quotation layout assembled for this document.",
  icon: Building2,
  iconClass: "bg-red-50 text-red-500",
  sections: ["company", "client", "items", "summary", "terms"],
};