module.exports = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  ASSIGN: "ASSIGN",
  STATUS_CHANGE: "STATUS_CHANGE",
  STAGE_CHANGE: "STAGE_CHANGE",
  CONVERT: "CONVERT",
  CONVERSION_REQUESTED: "CONVERSION_REQUESTED",
  CONVERSION_APPROVED: "CONVERSION_APPROVED",
  NOTE: "NOTE",
};
